[character]
name = "Sam Sottofrasca"
class = "Ladro"
level = "5"
race = "Mezzuomo"
background = "Investigatore"
alignement = "Caotico Neutrale"
experience_points = "1058"

[player]
name = "Raffa"

[stats]
strength = "10"
dexterity = "17"
constitution = "12"
intelligence = "14"
wisdom = "10"
charisma = "14"

[skills]

inspiration = "1"
proficiency_bonus = "3"

[skills.saving_throws]

strength = "10"
dexterity = "12"
constitution = "12"
intelligence = "12"
wisdom = "12"
charisma = "12"

[skills.skills]

acrobatics = "10"
animal_handling = "12"
arcana = "12"
athletics = "12"
deception = "12"
history = "12"
insight = "12"
intimidation = "12"
investigation = "12"
medicine = "12"
nature = "12"
perception = "12"
performance = "12"
persuasion = "12"
religion = "12"
sleight_of_hand = "12"
stealth = "12"
survival = "12"
