[character]
name = "Sam Sottofrasca"
class = "Ladro"
level = "5"
race = "Mezzuomo"
background = "Investigatore"
alignement = "Caotico Neutrale"
experience_points = "1058"

[player]
name = "Raffa"

[stats]
strength = "10"
dexterity = "17"
constitution = "12"
intelligence = "14"
wisdom = "10"
charisma = "14"

[skills]

inspiration = "1"
proficiency_bonus = "3"

[skills.saving_throws]

strength = "10"
