[character]
name = "Sam Sottofrasca"
class = "Ladro"
level = "5"
race = "Mezzuomo"
background = "Investigatore"
alignement = "Caotico Neutrale"
experience_points = "1058"

[player]
name = "Raffa"

[stats]
strength = "10"
dexterity = "17"
constitution = "12"
intelligence = "14"
wisdom = "10"
charisma = "14"

[skills]

inspiration = "1"

[skills.saving_throws_prof]
# "" for normal, "*" for proficiency , "**" for mastery, "+x" other bonus (not implemented yet)
strength = "*"
dexterity = "**"
constitution = ""
intelligence = ""
wisdom = ""
charisma = ""

[skills.skills_prof]
acrobatics = "*"
animal_handling = "**"
arcana = ""
athletics = ""
deception = ""
history = ""
insight = ""
intimidation = ""
investigation = ""
medicine = ""
nature = ""
perception = ""
performance = ""
persuasion = ""
religion = ""
sleight_of_hand = ""
stealth = "**"
survival =""